/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package lanchat2;

import java.awt.event.KeyEvent;
import java.io.BufferedReader;
import java.io.File;
import java.io.IOException;
import java.io.InputStreamReader;
import java.io.PrintStream;
import java.net.Socket;
import java.util.logging.Level;
import java.util.logging.Logger;

/**
 *
 * @author Le Phu Trong Ngan
 */
public class ClientChat extends javax.swing.JFrame {
    Socket s;
    BufferedReader br;
    PrintStream ps;
    Thread tClient;
    /**
     * Creates new form ClientChat
     */
    public ClientChat() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnSendClient = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtContentClient = new javax.swing.JTextArea();
        btnConnectClient = new javax.swing.JButton();
        txtHost = new javax.swing.JTextField();
        txtPortClient = new javax.swing.JFormattedTextField();
        jLabel3 = new javax.swing.JLabel();
        txtMessengerClient = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setName("Client"); // NOI18N

        btnSendClient.setIcon(new javax.swing.ImageIcon(getClass().getResource("/hinhanh/if_send-user_46836.png"))); // NOI18N
        btnSendClient.setText("Send");
        btnSendClient.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSendClientActionPerformed(evt);
            }
        });

        jLabel1.setText("Host");

        jLabel2.setText("Port");

        txtContentClient.setColumns(20);
        txtContentClient.setRows(5);
        jScrollPane1.setViewportView(txtContentClient);

        btnConnectClient.setIcon(new javax.swing.ImageIcon(getClass().getResource("/hinhanh/if_16_1751363.png"))); // NOI18N
        btnConnectClient.setText("Connect");
        btnConnectClient.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnConnectClientActionPerformed(evt);
            }
        });

        txtPortClient.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtPortClientKeyPressed(evt);
            }
        });

        jLabel3.setText("Messenger");

        txtMessengerClient.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtMessengerClientKeyPressed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtHost, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtPortClient)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnConnectClient))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(txtMessengerClient, javax.swing.GroupLayout.PREFERRED_SIZE, 230, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 24, Short.MAX_VALUE)
                        .addComponent(btnSendClient)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2)
                    .addComponent(btnConnectClient)
                    .addComponent(txtHost, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtPortClient, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 196, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 11, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(txtMessengerClient, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnSendClient))
                .addGap(16, 16, 16))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnConnectClientActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnConnectClientActionPerformed
        try {
            s= new Socket(txtHost.getText(),Integer.parseInt(txtPortClient.getText()));
            br= new BufferedReader(new InputStreamReader(s.getInputStream()));
            ps=new PrintStream(s.getOutputStream());
            
            getdata();
        } catch (IOException ex) {
            Logger.getLogger(ClientChat.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btnConnectClientActionPerformed
     void getdata()
     {
         tClient =new Thread(() -> {
             // nhận dữ liệu tư server
             String content;
             File file=new File("hinhanh//if_16_1751363.png");
             try {
                 
                 while((content=br.readLine())!=null)
                 {
                     txtContentClient.append("Server: "+content+"\n");
                 }  } catch (IOException ex) {
                     Logger.getLogger(ClientChat.class.getName()).log(Level.SEVERE, null, ex);
                 }
         });
         tClient.start();
     }
    
    
    private void btnSendClientActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSendClientActionPerformed
       //gửi nội dung chat từ  Client qua Server
       if(!"".equals(txtMessengerClient.getText()))
       {
           ps.println(txtMessengerClient.getText());
           txtContentClient.append("Client: "+txtMessengerClient.getText()+"\n");
       }
       txtMessengerClient.setText("");
       
    }//GEN-LAST:event_btnSendClientActionPerformed

    private void txtMessengerClientKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtMessengerClientKeyPressed
        if(evt.getKeyCode()==KeyEvent.VK_ENTER)
        {
             //gửi nội dung chat từ  Client qua Server
                if(!"".equals(txtMessengerClient.getText()))
               {
                 ps.println(txtMessengerClient.getText());
                      txtContentClient.append("Client: "+txtMessengerClient.getText()+"\n");
                 }
                txtMessengerClient.setText("");
        }
    }//GEN-LAST:event_txtMessengerClientKeyPressed

    private void txtPortClientKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtPortClientKeyPressed
       if(evt.getKeyCode()==KeyEvent.VK_ENTER)
       {
           
             try {
            s= new Socket(txtHost.getText(),Integer.parseInt(txtPortClient.getText()));
            br= new BufferedReader(new InputStreamReader(s.getInputStream()));
            ps=new PrintStream(s.getOutputStream());
            
            getdata();
        } catch (IOException ex) {
            Logger.getLogger(ClientChat.class.getName()).log(Level.SEVERE, null, ex);
        }
       }
    }//GEN-LAST:event_txtPortClientKeyPressed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ClientChat.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ClientChat.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ClientChat.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ClientChat.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ClientChat().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnConnectClient;
    private javax.swing.JButton btnSendClient;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea txtContentClient;
    private javax.swing.JTextField txtHost;
    private javax.swing.JTextField txtMessengerClient;
    private javax.swing.JFormattedTextField txtPortClient;
    // End of variables declaration//GEN-END:variables
}
